# This is a basic workflow to help you get started with Actions

name: PUBLISHING ON crates.io

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "publish"
  publish:
    name: Publish
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
      RUST_CHANNEL: "stable"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      # Install Rust toolchain
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update ${{ env.RUST_CHANNEL }}
          rustup component add --toolchain ${{ env.RUST_CHANNEL }} rustfmt rust-src
          rustup default ${{ env.RUST_CHANNEL }}

      # Before publishing check warnings and errors
      - name: Publishing check
        run: cargo publish --dry-run

      # Publish to crates.io
      - name: Publish to crates.io
        run: cargo publish --token ${CRATES_TOKEN}
